# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-21 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
